# frozen_string_literal: true

require 'bcrypt'
require 'colorize'
require 'date'
require 'i18n'
require 'terminal-table'
require 'uri'
require 'yaml'
require_relative 'app/menu'
require_relative 'app/output_cars_table'
require_relative 'app/sort'
require_relative 'app/user/authentication'
require_relative 'app/user/user'
require_relative 'locale'
